version: 2

models:
  - name: fact_sessions
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: session_id
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id

  - name: dim_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null
      - name: plan_tier
        tests:
          - not_null   
